"""empty message

Revision ID: 0003
Revises: 0002
Create Date: 2016-09-04 07:37:22.641113

"""

# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'projects', ['client_id', 'name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    ### end Alembic commands ###
